[package]
name = "cssinliner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kuchiki = { version = "0.8.1" }
html5ever = "*"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
